site_name: "Katxupa"
site_description: "Delicious Dish for Typescript and JavaScript projects"
edit_uri: "edit/main/docs/"
repo_url: "https://github.com/manusant/Katxupa"
site_url: "https://manusant.github.io/Katxupa"
site_author: Manuel Santos <ney.br.santos@gmail.com>

nav:
  - Home:
      - Overview: index.md
      - Contributors: index.md
  - Scope:
      - Scope Functions: scope.md
      - Initializer Functions: index2.md
  - Type Extensions:
      - String: index.md
      - Number: index.md
      - Boolean: index.md
      - Array: array.md
      - Map: index.md
      - Set: index.md

# Extensions
markdown_extensions:
  - admonition
  - abbr
  - attr_list
  - def_list
  - footnotes
  - tables
  - fenced_code
  - meta
  - wikilinks
  - md_in_html
  - sane_lists
  - toc:
      # permalink: true
      permalink: '#'
      baselevel: 1
      separator: '_'
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.details
  - pymdownx.highlight:
      linenums: true
      anchor_linenums: true
      auto_title: true
  - pymdownx.inlinehilite
  - pymdownx.mark
  - pymdownx.keys
  - pymdownx.magiclink:
      repo_url_shorthand: true
      user: squidfunk
      repo: mkdocs-material
  - pymdownx.snippets:
      auto_append:
        - docs/assets/abbreviations.md
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format

theme:
  name: material
  language: en
  features:
    - content.code.copy
    - content.code.select
    - content.code.annotate
    - content.code.annotate
    - navigation.instant
    - navigation.tabs.sticky
    - navigation.tabs
    - header.autohide
    - announce.dismiss
    - search.suggest
    - search.share
    - navigation.footer
  palette:
    - scheme: default
      primary: black
      accent: light blue
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
    - scheme: slate
      primary: black
      accent: light blue
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode
  font:
    text: Roboto
    code: Roboto Mono